"""add scheduler heartbeats table

Revision ID: 51023dc9d8da
Revises: 3bd0a024a8df
Create Date: 2026-08-31 15:14:22.960852

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '51023dc9d8da'
down_revision: Union[str, Sequence[str], None] = '3bd0a024a8df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_heartbeats',
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_heartbeats')
    # ### end Alembic commands ###
