"""add api key usage daily and hourly tables

Revision ID: 4c5c282fdaf0
Revises: 882ea5b5f80c
Create Date: 2026-09-27 15:47:35.243964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c5c282fdaf0'
down_revision: Union[str, Sequence[str], None] = '882ea5b5f80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_usage_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_limit_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_limit_key', 'date', name='uq_usage_daily_key_date')
    )
    op.create_index(op.f('ix_api_key_usage_daily_date'), 'api_key_usage_daily', ['date'], unique=False)
    op.create_index(op.f('ix_api_key_usage_daily_rate_limit_key'), 'api_key_usage_daily', ['rate_limit_key'], unique=False)
    op.create_table('api_key_usage_hourly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_limit_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_limit_key', 'hour', name='uq_usage_hourly_key_hour')
    )
    op.create_index(op.f('ix_api_key_usage_hourly_hour'), 'api_key_usage_hourly', ['hour'], unique=False)
    op.create_index(op.f('ix_api_key_usage_hourly_rate_limit_key'), 'api_key_usage_hourly', ['rate_limit_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_key_usage_hourly_rate_limit_key'), table_name='api_key_usage_hourly')
    op.drop_index(op.f('ix_api_key_usage_hourly_hour'), table_name='api_key_usage_hourly')
    op.drop_table('api_key_usage_hourly')
    op.drop_index(op.f('ix_api_key_usage_daily_rate_limit_key'), table_name='api_key_usage_daily')
    op.drop_index(op.f('ix_api_key_usage_daily_date'), table_name='api_key_usage_daily')
    op.drop_table('api_key_usage_daily')
    # ### end Alembic commands ###
