"""add goal_events

Revision ID: 5a33b602e191
Revises: 54a568cba252
Create Date: 2026-09-13 16:39:10.395966

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a33b602e191"
down_revision: Union[str, Sequence[str], None] = "54a568cba252"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goal_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("player_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "assist_player_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("minute", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fixture_id", "minute", "player_name", "kind", name="uq_goal_events_natural"
        ),
    )
    op.create_index("ix_goal_events_fixture", "goal_events", ["fixture_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_goal_events_fixture", table_name="goal_events")
    op.drop_table("goal_events")
    # ### end Alembic commands ###
