"""add odds

Revision ID: 7b2f2bcd6f7b
Revises: 5a33b602e191
Create Date: 2026-09-13 16:58:20.246490

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7b2f2bcd6f7b'
down_revision: Union[str, Sequence[str], None] = '5a33b602e191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('home', sa.Float(), nullable=True),
    sa.Column('draw', sa.Float(), nullable=True),
    sa.Column('away', sa.Float(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'bookmaker', name='uq_odds_fixture_bookmaker')
    )
    op.create_index('ix_odds_fixture', 'odds', ['fixture_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_odds_fixture', table_name='odds')
    op.drop_table('odds')
    # ### end Alembic commands ###
