"""add display_name to teams

Adds the column (autogenerated) and backfills it, so existing rows are
correct immediately rather than waiting for the next sync of each team.

The backfill applies short_name as the default and then the curated
overrides on top, mirroring what display_name() does on write. Those are
written out as literals here on purpose: a migration should reproduce the
same result whenever it runs, and importing the override map would make
this migration's behaviour change every time someone edits that file.

Revision ID: 54a568cba252
Revises: d7ad2d870ee3
Create Date: 2026-09-13 08:36:16.465236

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54a568cba252"
down_revision: Union[str, Sequence[str], None] = "d7ad2d870ee3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams",
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(
        op.f("ix_teams_display_name"), "teams", ["display_name"], unique=False
    )
    # ### end Alembic commands ###

    # Default: whatever upstream already gave us.
    op.execute("UPDATE teams SET display_name = COALESCE(short_name, name)")

    # Then the curated corrections, mirroring display_name() on the write
    # path. Written out as literals on purpose: a migration should produce
    # the same result whenever it runs, and importing the override map
    # would make this migration's behaviour change every time someone
    # edited that file.
    for team_name, display in (
        ("Club Atlético de Madrid", "Atlético Madrid"),
        ("FC Barcelona", "Barcelona"),
        ("Athletic Club", "Athletic Bilbao"),
        ("Real Racing Club de Santander", "Racing Santander"),
        ("Nottingham Forest FC", "Nottingham Forest"),
        ("Brighton & Hove Albion FC", "Brighton"),
        ("1. FC Köln", "Köln"),
        ("Sevilla FC", "Sevilla"),
    ):
        op.execute(
            sa.text(
                "UPDATE teams SET display_name = :display WHERE name = :name"
            ).bindparams(display=display, name=team_name)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_teams_display_name"), table_name="teams")
    op.drop_column("teams", "display_name")
    # ### end Alembic commands ###
