"""stable internal ids and external_ids mapping

Gateway rows stop being keyed by the upstream provider's id and get their
own, with provider ids moved into the `external_ids` mapping table.

The autogenerated part (creating external_ids) is kept as produced. Two
things are added by hand:

1. The existing rows are cleared. Their primary keys *are* provider ids,
   so they cannot stay. This is safe here in a way it would not be for an
   application database: this schema is a cache of upstream data, fully
   rebuildable by re-syncing, and holds only the current season. Rewriting
   primary keys across six dependent tables would be far more risk than
   the ~1,500 rows it protects. Run a sync after upgrading.

2. The id sequences are moved above every provider range in use.
   football-data.org numbers teams from 1 and fixtures around 560,000;
   api-sports fixtures are around 1,500,000. Starting at 10,000,000 keeps
   gateway ids and provider ids disjoint, so a consumer migrating between
   the two can hold both in one column without collision.

Revision ID: 2352f037497e
Revises: 51023dc9d8da
Create Date: 2026-09-12 14:15:46.461590

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

from app.db.models.external_id import ID_SEQUENCE_START

# revision identifiers, used by Alembic.
revision: str = "2352f037497e"
down_revision: Union[str, Sequence[str], None] = "51023dc9d8da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_ids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "entity_type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "external_id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("internal_id", sa.Integer(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_type", "source", "external_id", name="uq_external_ids_source_ref"
        ),
    )
    op.create_index(
        "ix_external_ids_internal",
        "external_ids",
        ["entity_type", "internal_id"],
        unique=False,
    )
    op.create_index(
        "ix_external_ids_lookup",
        "external_ids",
        ["entity_type", "source", "external_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Existing rows are keyed by provider ids - see the module docstring.
    # CASCADE reaches the dependent stat tables; RESTART IDENTITY resets
    # the sequences before the floor below is applied.
    op.execute(
        "TRUNCATE TABLE "
        "shot_events, player_match_stats, team_match_stats, "
        "player_stats, standings, fixtures, teams, leagues "
        "RESTART IDENTITY CASCADE"
    )

    # START WITH as well as RESTART: RESTART alone is undone by the next
    # TRUNCATE ... RESTART IDENTITY, which would drop the floor back to 1.
    for table in ("leagues", "teams", "fixtures"):
        op.execute(f"ALTER SEQUENCE {table}_id_seq START WITH {ID_SEQUENCE_START}")
        op.execute(f"ALTER SEQUENCE {table}_id_seq RESTART WITH {ID_SEQUENCE_START}")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_external_ids_lookup", table_name="external_ids")
    op.drop_index("ix_external_ids_internal", table_name="external_ids")
    op.drop_table("external_ids")
    # ### end Alembic commands ###

    # Downgrading leaves the tables empty rather than restoring provider
    # ids - the mapping that would make that possible is the thing being
    # dropped. Re-sync after downgrading.
    op.execute(
        "TRUNCATE TABLE "
        "shot_events, player_match_stats, team_match_stats, "
        "player_stats, standings, fixtures, teams, leagues "
        "RESTART IDENTITY CASCADE"
    )
    for table in ("leagues", "teams", "fixtures"):
        op.execute(f"ALTER SEQUENCE {table}_id_seq START WITH 1")
        op.execute(f"ALTER SEQUENCE {table}_id_seq RESTART WITH 1")
