"""player match stats team match stats shot events

Revision ID: 3bd0a024a8df
Revises: b3d7a4540234
Create Date: 2026-08-21 08:41:06.735453

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bd0a024a8df"
down_revision: Union[str, Sequence[str], None] = "b3d7a4540234"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_match_stats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "external_ref", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("player_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("goals", sa.Integer(), nullable=False),
        sa.Column("own_goals", sa.Integer(), nullable=False),
        sa.Column("shots", sa.Integer(), nullable=False),
        sa.Column("xg", sa.Float(), nullable=False),
        sa.Column("xg_chain", sa.Float(), nullable=False),
        sa.Column("xg_buildup", sa.Float(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("xa", sa.Float(), nullable=False),
        sa.Column("key_passes", sa.Integer(), nullable=False),
        sa.Column("yellow_cards", sa.Integer(), nullable=False),
        sa.Column("red_cards", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fixture_id",
            "source",
            "external_ref",
            name="uq_player_match_stat_fixture_source_ref",
        ),
    )
    op.create_table(
        "shot_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "external_ref", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("player_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "assist_player_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("minute", sa.Integer(), nullable=False),
        sa.Column("xg", sa.Float(), nullable=False),
        sa.Column("location_x", sa.Float(), nullable=False),
        sa.Column("location_y", sa.Float(), nullable=False),
        sa.Column(
            "body_part", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.Column(
            "situation", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True
        ),
        sa.Column("result", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_ref", name="uq_shot_event_source_ref"),
    )
    op.create_table(
        "team_match_stats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("expected_points", sa.Float(), nullable=False),
        sa.Column("goals", sa.Integer(), nullable=False),
        sa.Column("xg", sa.Float(), nullable=False),
        sa.Column("np_xg", sa.Float(), nullable=False),
        sa.Column("np_xg_difference", sa.Float(), nullable=False),
        sa.Column("ppda", sa.Float(), nullable=False),
        sa.Column("deep_completions", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fixture_id", "team_id", name="uq_team_match_stat_fixture_team"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_match_stats")
    op.drop_table("shot_events")
    op.drop_table("player_match_stats")
    # ### end Alembic commands ###
